name: faunadb_http
version: 0.14.4
description: A pure Dart implementation of a FaunaDB client and provides query classes that closely mimic FQL functions.
homepage: https://github.com/gavanitrate/faunadb-http-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.2
  json_annotation: ^4.1.0

dev_dependencies:
  json_serializable: ^5.0.0
  build_runner: ^2.0.6
  pedantic: ^1.11.1
